Repository lokalise/shared-ts-libs, pull requests merged in 2024-09, with the labels that each got.

#312 Improving spies doc
  packages/app/background-jobs-common/README.md
Labels: patch

#329 fix: move vite/vitest dependencies to peerDependencies
  packages/dev/package-vite-config/package.json
Labels: patch

#330 AP-4770 method for extracting translatable text pieces
  packages/app/non-translatable-markup/src/index.ts
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.spec.ts
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.ts
Labels: minor

#333 Adding index files to universal-ts-utils
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/vitest.config.mts
Labels: minor

#334 Feature/extract text between tags options
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.spec.ts
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.ts
Labels: minor

#341 Trying to fix node import for BE
  packages/app/universal-ts-utils/package.json
Labels: patch

#342 Another try to fix node import
  packages/app/universal-ts-utils/src/node.ts
Labels: patch

#344 Bugfix/universal ts utils fe import fix
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/package.json
Labels: major

#346 Trigger error-utils release
  packages/app/error-utils/package.json
Labels: minor

#345 package.json applying recommendations
  packages/app/universal-ts-utils/package.json
Labels: patch
