Repository lokalise/shared-ts-libs, pull requests merged in 2024-08, with the labels that each got.

#256 Add reusable healthcheck functionality
  .github/workflows/release.healthcheck-utils.yml
  packages/app/healthcheck-utils/.gitignore
  packages/app/healthcheck-utils/LICENSE.md
  packages/app/healthcheck-utils/README.md
  packages/app/healthcheck-utils/biome.json
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
  packages/app/healthcheck-utils/src/healthchecks.ts
  packages/app/healthcheck-utils/src/index.ts
  packages/app/healthcheck-utils/tsconfig.json
  packages/app/healthcheck-utils/tsconfig.lint.json
  packages/app/healthcheck-utils/vitest.config.mts
Labels: minor

#257 Extract reusable periodic job
  packages/app/healthcheck-utils/.env.test
  packages/app/healthcheck-utils/docker-compose.yml
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/src/AbstractPeriodicJob.ts
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
  packages/app/healthcheck-utils/src/healthchecks.ts
  packages/app/healthcheck-utils/src/index.ts
  packages/app/healthcheck-utils/test/setup.ts
  packages/app/healthcheck-utils/vitest.config.mts
Labels: minor

#258 Use separate checks for separate healthchecks
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
  packages/app/healthcheck-utils/src/healthchecks.ts
Labels: patch

#259 Lint fix
  packages/app/healthcheck-utils/package.json
Labels: skip-release

#261 NTC-biome
  packages/app/background-jobs-common/package.json
  packages/app/non-translatable-markup/.eslintignore
  packages/app/non-translatable-markup/.eslintrc.json
  packages/app/non-translatable-markup/.gitignore
  packages/app/non-translatable-markup/.prettierignore
  packages/app/non-translatable-markup/biome.json
  packages/app/non-translatable-markup/package.json
  packages/app/non-translatable-markup/src/nonTranslatableContentHelper.ts
  packages/app/non-translatable-markup/test/nonTranslatableContentHelper.spec.ts
  packages/app/non-translatable-markup/tsconfig.json
  packages/app/non-translatable-markup/tsconfig.lint.json
  packages/app/non-translatable-markup/vite.config.ts
Labels: skip-release

#262 NTC minor refactor
  packages/app/non-translatable-markup/src/index.ts
  packages/app/non-translatable-markup/src/methods/index.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.spec.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.ts
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.spec.ts
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.ts
  packages/app/non-translatable-markup/src/methods/utils.ts
  packages/app/non-translatable-markup/src/nonTranslatableTags.ts
  packages/app/non-translatable-markup/test/nonTranslatableContentHelper.spec.ts
  packages/app/non-translatable-markup/vite.config.ts
Labels: patch

#263 Add AbstractPeriodicJob to the bg job lib
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/index.ts
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
  packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
  packages/app/background-jobs-common/src/periodic-jobs/periodicJobUtils.ts
  packages/app/background-jobs-common/test/TestRedis.ts
  packages/app/background-jobs-common/test/dependencyMocks.ts
  packages/app/background-jobs-common/test/fakes/FakePeriodicJob.ts
  packages/app/background-jobs-common/vitest.config.mts
  packages/app/non-translatable-markup/package.json
Labels: minor

#264 Support multiple releases
  .github/workflows/release.package.yml
  packages/app/backend-http-client/package.json
  packages/app/background-jobs-common/package.json
  packages/app/non-translatable-markup/package.json
Labels: minor

#266 Applying lint fixes
  packages/app/backend-http-client/package.json
  packages/app/background-jobs-common/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/prisma-utils/package.json
  packages/app/universal-ts-utils/package.json
  packages/dev/package-vite-config/package.json
Labels: skip-release

#267 Fixing missing export
  packages/app/non-translatable-markup/src/index.ts
  packages/app/non-translatable-markup/src/methods/index.ts
Labels: patch

#269 Fixing lint issue
  packages/app/non-translatable-markup/package.json
  packages/dev/biome-config/.prettierignore
Labels: skip-release

#268 Provide protected getter for queue and worker
  biome.json
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: minor

#270 id-utils biome
  packages/app/background-jobs-common/vitest.config.mts
  packages/app/id-utils/.eslintignore
  packages/app/id-utils/.eslintrc.json
  packages/app/id-utils/.prettierignore
  packages/app/id-utils/biome.json
  packages/app/id-utils/package.json
  packages/app/id-utils/src/index.spec.ts
  packages/app/id-utils/src/index.ts
  packages/app/id-utils/tsconfig.json
  packages/app/id-utils/tsconfig.lint.json
  packages/app/id-utils/vite.config.ts
Labels: skip-release

#271 Add cron support
  packages/app/background-jobs-common/src/index.ts
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
  packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
  packages/app/background-jobs-common/test/fakes/FakePeriodicJob.ts
Labels: major

#265 AP-4762 Symbols detection
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.spec.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.ts
  packages/app/non-translatable-markup/src/methods/utils.ts
  packages/app/non-translatable-markup/vite.config.ts
Labels: minor

#272 prismaTansaction retrying server closed error
  packages/app/prisma-utils/src/errors/prismaError.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
Labels: minor

#273 Covering isPrismaUnableToStartTransactionInTimeError
  packages/app/prisma-utils/src/errors/prismaError.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
Labels: minor

#274 Migrate to reusable AbstractPeriodicJob
  .github/workflows/ci.yml
  package.json
  packages/app/healthcheck-utils/biome.json
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/src/AbstractPeriodicJob.ts
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.ts
  packages/app/healthcheck-utils/src/index.ts
Labels: minor

#275 fix job export
  packages/app/healthcheck-utils/src/index.ts
Labels: patch

#279 Adjust indent width and add missing extension
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/mock-data/mockProduct1.json
  packages/app/backend-http-client/src/client/mock-data/mockProductsLimit3.json
  packages/app/backend-http-client/tsconfig.json
  packages/app/backend-http-client/tsconfig.lint.json
  packages/app/backend-http-client/vitest.config.mts
  packages/app/background-jobs-common/biome.json
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/tsconfig.json
  packages/app/background-jobs-common/tsconfig.lint.json
  packages/app/background-jobs-common/vitest.config.mts
  packages/app/healthcheck-utils/biome.json
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/tsconfig.json
  packages/app/healthcheck-utils/tsconfig.lint.json
  packages/app/healthcheck-utils/vitest.config.mts
  packages/app/id-utils/biome.json
  packages/app/id-utils/package.json
  packages/app/id-utils/tsconfig.json
  packages/app/id-utils/tsconfig.lint.json
  packages/app/non-translatable-markup/biome.json
  packages/app/non-translatable-markup/package.json
  packages/app/non-translatable-markup/tsconfig.json
  packages/app/non-translatable-markup/tsconfig.lint.json
  packages/app/prisma-utils/biome.json
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/tsconfig.json
  packages/app/prisma-utils/tsconfig.lint.json
  packages/app/prisma-utils/vite.config.ts
  packages/app/prisma-utils/vitest.config.mts
  packages/app/universal-ts-utils/biome.json
  packages/app/universal-ts-utils/package.json
  packages/app/universal-ts-utils/tsconfig.json
  packages/app/universal-ts-utils/tsconfig.lint.json
  packages/app/universal-ts-utils/vitest.config.mts
  packages/dev/biome-config/configs/biome-base.jsonc
  packages/dev/biome-config/configs/biome-esm.jsonc
  packages/dev/biome-config/configs/biome-frontend.jsonc
  packages/dev/biome-config/configs/biome-package.jsonc
  packages/dev/biome-config/package.json
  packages/dev/package-vite-config/biome.json
  packages/dev/package-vite-config/package.json
  packages/dev/package-vite-config/tsconfig.json
Labels: minor

#280 feat: Compare string arrays
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/array/areStringArraysEqual.spec.ts
  packages/app/universal-ts-utils/src/array/areStringArraysEqual.ts
Labels: minor

#281 fix: define package-version script in package.json
  packages/app/universal-ts-utils/package.json
Labels: minor

#283 Prisma utils build fix
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/vite.config.ts
  packages/app/prisma-utils/vitest.config.mts
Labels: skip-release

#282 Prisma client builder
  packages/app/prisma-utils/src/index.ts
  packages/app/prisma-utils/src/prismaClientFactory.mock.spec.ts
  packages/app/prisma-utils/src/prismaClientFactory.spec.ts
  packages/app/prisma-utils/src/prismaClientFactory.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/prisma-utils/src/types.ts
  packages/app/prisma-utils/test/getDatasourceUrl.ts
Labels: major

#284 prisma utils trying to fix build issue
  packages/app/prisma-utils/src/types.ts
  packages/app/prisma-utils/tsconfig.json
Labels: patch

#285 Trying to fix prisma-utils build issue
  packages/app/prisma-utils/package.json
Labels: patch

#286 another prisma-utils build fix
  packages/app/prisma-utils/package.json
Labels: patch

#287 Prisma constructor as parameter to prismaClientFactory
  packages/app/prisma-utils/src/prismaClientFactory.mock.spec.ts
  packages/app/prisma-utils/src/prismaClientFactory.spec.ts
  packages/app/prisma-utils/src/prismaClientFactory.ts
Labels: major

#288 Add support for barriers
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/barrier/barrier.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.barrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/src/index.ts
  packages/app/background-jobs-common/test/processors/TestBarrierBackgroundJobProcessor.ts
Labels: minor

#289 Implement child job throttling barrier
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/barrier/JobQueueSizeThrottlingBarrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/barrier/JobQueueSizeThrottlingBarrier.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.spec.ts
  packages/app/background-jobs-common/src/index.ts
  packages/app/background-jobs-common/test/dependencyMocks.ts
  packages/app/background-jobs-common/test/processors/TestForeverRescheduledBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestQueueSizeJobBarrierBackgroundJobProcessor.ts
Labels: major

#290 Add node-core peer dependency
  packages/app/error-utils/.eslintignore
  packages/app/error-utils/.eslintrc.json
  packages/app/error-utils/.prettierignore
  packages/app/error-utils/biome.json
  packages/app/error-utils/package.json
  packages/app/error-utils/src/bugsnag.spec.ts
  packages/app/error-utils/src/bugsnag.ts
  packages/app/error-utils/tsconfig.json
  packages/app/error-utils/tsconfig.lint.json
  packages/app/error-utils/vitest.config.mts
Labels: major

#292 fix error-utils
  packages/app/error-utils/package.json
Labels: skip-release

#291 Fix interval
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: patch

#293 get job count lazy init
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/prisma-utils/src/prismaClientFactory.spec.ts
Labels: patch

#298 Improving error report context
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: patch

#299 Text only with HTML markup is not translatable
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.ts
  packages/app/non-translatable-markup/src/methods/utils.ts
Labels: minor

#302 MET-188 Add support for repeatable jobs
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.ts
  packages/app/background-jobs-common/src/background-job-processor/types.ts
Labels: minor

#300 Protected queue and worker types exposed
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
Labels: minor

#304 Improving bg common logging
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: minor

#301 Defaulting to streams.events.maxLen as 0
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/constants.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
Labels: minor

#309 Adding isNonEmptyArray
  packages/app/universal-ts-utils/src/array/isNonEmptyArray.spec.ts
  packages/app/universal-ts-utils/src/array/isNonEmptyArray.ts
Labels: minor

#311 Keeping completed jobs a max of 3 days
  packages/app/background-jobs-common/src/background-job-processor/constants.ts
Labels: minor

#310 AP-5015 extend redis config sanitization
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/index.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/backgroundJobProcessorGetActiveQueueIds.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
Labels: minor
