Repository lokalise/shared-ts-libs, pull requests merged in 2024-12, with the labels that each got.

#393 Vault env var sync indicates that 403 might be due to invalid path.
  packages/app/script-utils/src/vault/vault.ts
Labels: patch

#400 Universal-ts-utils migrating node-core object utils
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/object/__snapshots__/copyWithoutNullish.spec.ts.snap
  packages/app/universal-ts-utils/src/public/object/convertDateFieldsToIsoString.spec.ts
  packages/app/universal-ts-utils/src/public/object/convertDateFieldsToIsoString.ts
  packages/app/universal-ts-utils/src/public/object/copyWithoutEmpty.spec.ts
  packages/app/universal-ts-utils/src/public/object/copyWithoutEmpty.ts
  packages/app/universal-ts-utils/src/public/object/copyWithoutNullish.spec.ts
  packages/app/universal-ts-utils/src/public/object/copyWithoutNullish.ts
  packages/app/universal-ts-utils/src/public/object/deepClone.spec.ts
  packages/app/universal-ts-utils/src/public/object/deepClone.ts
  packages/app/universal-ts-utils/src/public/object/groupByPath.spec.ts
  packages/app/universal-ts-utils/src/public/object/groupByPath.ts
  packages/app/universal-ts-utils/src/public/object/isEmpty.spec.ts
  packages/app/universal-ts-utils/src/public/object/isEmpty.ts
  packages/app/universal-ts-utils/src/public/object/pick.spec.ts
  packages/app/universal-ts-utils/src/public/object/pick.ts
  packages/app/universal-ts-utils/src/public/object/transformToKebabCase.spec.ts
  packages/app/universal-ts-utils/src/public/object/transformToKebabCase.ts
Labels: minor

#401 Migrate to undici 7
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/httpClient.ts
Labels: major

#403 Make abstract periodic job configuration more flexible
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
  packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
Labels: patch

#409 Fix Redis check
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
Labels: patch

#410 Prisma range version
  packages/app/prisma-utils/package.json
Labels: patch

#414 Trying to fix lint
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/fakes/FakePeriodicJob.ts
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
Labels: skip-release

#412 Type utils and wait and retry from node-core
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/object/__snapshots__/copyWithoutNullish.spec.ts.snap
  packages/app/universal-ts-utils/src/public/object/copyWithoutNullish.spec.ts
  packages/app/universal-ts-utils/src/public/type/hasMessage.spec.ts
  packages/app/universal-ts-utils/src/public/type/hasMessage.ts
  packages/app/universal-ts-utils/src/public/type/isError.spec.ts
  packages/app/universal-ts-utils/src/public/type/isError.ts
  packages/app/universal-ts-utils/src/public/type/isObject.spec.ts
  packages/app/universal-ts-utils/src/public/type/isObject.ts
  packages/app/universal-ts-utils/src/public/type/isStandardizedError.spec.ts
  packages/app/universal-ts-utils/src/public/type/isStandardizedError.ts
  packages/app/universal-ts-utils/src/public/waitAndRetry.spec.ts
  packages/app/universal-ts-utils/src/public/waitAndRetry.ts
Labels: minor

#415 Update `eslint-config-biome-companion`
  packages/dev/eslint-config-biome-companion-frontend/README.md
Labels: skip-release

#416 Trim text util
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/string/trimText.spec.ts
  packages/app/universal-ts-utils/src/public/string/trimText.ts
Labels: minor

#417 Adding missing export
  packages/app/universal-ts-utils/src/node.ts
Labels: patch

#418 DXP-335 Universal-ts-utils doc
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/public/array/callChunked.ts
  packages/app/universal-ts-utils/src/public/array/chunk.ts
  packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.ts
  packages/app/universal-ts-utils/src/public/array/removeFalsy.ts
  packages/app/universal-ts-utils/src/public/array/removeNullish.ts
  packages/app/universal-ts-utils/src/public/array/sort.ts
  packages/app/universal-ts-utils/src/public/array/sortByField.ts
  packages/app/universal-ts-utils/src/public/array/unique.ts
  packages/app/universal-ts-utils/src/public/object/areDeepEqual.ts
  packages/app/universal-ts-utils/src/public/object/copyWithoutEmpty.ts
  packages/app/universal-ts-utils/src/public/object/copyWithoutNullish.ts
  packages/app/universal-ts-utils/src/public/object/deepClone.ts
  packages/app/universal-ts-utils/src/public/object/groupBy.ts
  packages/app/universal-ts-utils/src/public/object/groupByPath.ts
  packages/app/universal-ts-utils/src/public/object/groupByUnique.ts
  packages/app/universal-ts-utils/src/public/object/isEmpty.ts
  packages/app/universal-ts-utils/src/public/object/pick.ts
  packages/app/universal-ts-utils/src/public/object/transformToKebabCase.ts
  packages/app/universal-ts-utils/src/public/string/trimText.ts
  packages/app/universal-ts-utils/src/public/type/hasMessage.ts
  packages/app/universal-ts-utils/src/public/type/isError.ts
  packages/app/universal-ts-utils/src/public/type/isObject.ts
  packages/app/universal-ts-utils/src/public/type/isStandardizedError.ts
  packages/app/universal-ts-utils/src/public/waitAndRetry.ts
Labels: patch

#426 Remove dotenv
  packages/app/prisma-utils/.env
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/test/envSetupHook.ts
Labels: skip-release
