Repository lokalise/shared-ts-libs, pull requests merged in 2024-06, with the labels that each got.

#162 Extract context-related plugins
  .github/workflows/release.context-plugins.yml
  packages/app/context-plugins/.eslintignore
  packages/app/context-plugins/.eslintrc.json
  packages/app/context-plugins/.gitignore
  packages/app/context-plugins/LICENSE.md
  packages/app/context-plugins/README.md
  packages/app/context-plugins/package.json
  packages/app/context-plugins/src/index.ts
  packages/app/context-plugins/src/plugins/opentelemetry/prismaOtelTracingPlugin.ts
  packages/app/context-plugins/src/plugins/opentelemetry/spanProcessors.ts
  packages/app/context-plugins/src/plugins/requestContextProviderPlugin.spec.ts
  packages/app/context-plugins/src/plugins/requestContextProviderPlugin.ts
  packages/app/context-plugins/src/plugins/requestContextProviderPluginTypes.spec.ts
  packages/app/context-plugins/src/plugins/unhandledExceptionPlugin.spec.ts
  packages/app/context-plugins/src/plugins/unhandledExceptionPlugin.ts
  packages/app/context-plugins/tsconfig.json
  packages/app/context-plugins/tsconfig.lint.json
  packages/app/context-plugins/vitest.config.mts
Labels: skip-release

#163 feat: add shopify websockets room
  packages/app/websockets-common/src/rooms.ts
Labels: minor

#165 fix: update cursor as part of getPaginatedEntriesByHasMore
  packages/app/api-common/src/paginationUtils.ts
Labels: patch

#166 * improve pagination tests
  packages/app/api-common/src/paginationUtils.ts
  packages/app/api-common/test/paginationUtils.spec.ts
Labels: skip-release

#167 Extract error logic related to the http client
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/backend-http-client/src/client/mock-data/mockProduct1.json
  packages/app/backend-http-client/src/client/mock-data/mockProductsLimit3.json
  packages/app/backend-http-client/src/errors/ResponseStatusError.spec.ts
  packages/app/backend-http-client/src/errors/ResponseStatusError.ts
  packages/app/backend-http-client/tsconfig.json
Labels: minor

#168 Update dependencies
  packages/app/api-common/package.json
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/background-jobs-common/package.json
  packages/app/context-plugins/package.json
  packages/app/error-utils/package.json
  packages/app/events-common/package.json
  packages/app/id-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/prisma-utils/package.json
  packages/app/supported-languages/package.json
  packages/app/websockets-common/package.json
  packages/dev/eslint-config/package.json
  packages/dev/package-vite-config/package.json
Labels: minor

#169 Add dependabot ignores
  .github/dependabot.yml
Labels: skip-release

#181 Add test options
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/src/client/httpClient.ts
Labels: minor

#182 Add requestLabel to request zod errors
  packages/app/backend-http-client/.eslintrc.json
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
Labels: minor

#183 AP-3814 Added uuid 7.
  packages/app/id-utils/README.md
  packages/app/id-utils/package.json
  packages/app/id-utils/src/index.spec.ts
  packages/app/id-utils/src/index.ts
Labels: minor

#193 Filling errorDetails for unknown errors
  packages/app/error-utils/src/bugsnag.spec.ts
  packages/app/error-utils/src/bugsnag.ts
Labels: minor

#195 Job scheduled spy
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/types.ts
Labels: minor
