Repository lokalise/shared-ts-libs, pull requests merged in 2024-07, with the labels that each got.

#198 Use correct plugin version
  packages/dev/eslint-config/package.json
Labels: patch

#202 Updated createPaginatedReponse params description
  packages/app/api-common/src/paginationUtils.ts
Labels: patch

#203 Add base Biome config
  .github/workflows/release.biome-config.yml
  packages/dev/biome-config/.prettierignore
  packages/dev/biome-config/LICENSE.md
  packages/dev/biome-config/README.md
  packages/dev/biome-config/configs/biome-base.jsonc
  packages/dev/biome-config/configs/biome-esm.jsonc
  packages/dev/biome-config/configs/biome-frontend.jsonc
  packages/dev/biome-config/package.json
Labels: minor

#205 Accept any string as a correlationId
  packages/app/events-common/src/baseEventSchemas.ts
Labels: patch

#201 Transaction auto increase timeout
  packages/app/prisma-utils/src/prismaError.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/prisma-utils/src/types.ts
Labels: minor

#209 Switch backend client to biome
  biome.json
  packages/app/backend-http-client/.eslintignore
  packages/app/backend-http-client/.eslintrc.json
  packages/app/backend-http-client/.npmignore
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/backend-http-client/src/client/mock-data/mockProduct1.json
  packages/app/backend-http-client/src/client/mock-data/mockProductsLimit3.json
  packages/app/backend-http-client/src/errors/ResponseStatusError.spec.ts
  packages/app/backend-http-client/src/errors/ResponseStatusError.ts
  packages/app/backend-http-client/tsconfig.json
  packages/app/backend-http-client/tsconfig.lint.json
Labels: skip-release

#211 chore: move context-plugins to context-fastify-plugins folder
  .github/workflows/release.context-fastify-plugins.yml
  packages/app/context-fastify-plugins/.eslintignore
  packages/app/context-fastify-plugins/.eslintrc.json
  packages/app/context-fastify-plugins/.gitignore
  packages/app/context-fastify-plugins/LICENSE.md
  packages/app/context-fastify-plugins/README.md
  packages/app/context-fastify-plugins/package.json
  packages/app/context-fastify-plugins/src/index.ts
  packages/app/context-fastify-plugins/src/plugins/opentelemetry/prismaOtelTracingPlugin.ts
  packages/app/context-fastify-plugins/src/plugins/opentelemetry/spanProcessors.ts
  packages/app/context-fastify-plugins/src/plugins/requestContextProviderPlugin.spec.ts
  packages/app/context-fastify-plugins/src/plugins/requestContextProviderPlugin.ts
  packages/app/context-fastify-plugins/src/plugins/requestContextProviderPluginTypes.spec.ts
  packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.spec.ts
  packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.ts
  packages/app/context-fastify-plugins/tsconfig.json
  packages/app/context-fastify-plugins/tsconfig.lint.json
  packages/app/context-fastify-plugins/vitest.config.mts
Labels: skip-release

#212 Add isomorphic utils
  .github/workflows/release.package.yml
  .github/workflows/release.universal-ts-utils.yml
  packages/app/universal-ts-utils/.gitignore
  packages/app/universal-ts-utils/.npmignore
  packages/app/universal-ts-utils/LICENSE.md
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/package.json
  packages/app/universal-ts-utils/src/array/chunk.spec.ts
  packages/app/universal-ts-utils/src/array/chunk.ts
  packages/app/universal-ts-utils/src/array/removeFalsy.spec.ts
  packages/app/universal-ts-utils/src/array/removeFalsy.ts
  packages/app/universal-ts-utils/src/array/removeNullish.spec.ts
  packages/app/universal-ts-utils/src/array/removeNullish.ts
  packages/app/universal-ts-utils/tsconfig.json
  packages/app/universal-ts-utils/tsconfig.lint.json
  packages/app/universal-ts-utils/vitest.config.mts
Labels: skip-release

#213 Allow non-null assertions in tests
  packages/dev/biome-config/configs/biome-base.jsonc
Labels: minor

#214 Adding test files to biome override
  packages/dev/biome-config/configs/biome-base.jsonc
Labels: minor

#215 chore: allow comments within json files
  packages/dev/biome-config/configs/biome-base.jsonc
Labels: patch

#216 biome 1.2.0
  packages/dev/biome-config/package.json
Labels: skip-release

#217 biome - adding missing script required for release
  packages/dev/biome-config/package.json
Labels: skip-release

#220 fix: add vitest globals to biome base config
  packages/dev/biome-config/configs/biome-base.jsonc
Labels: patch

#221 fix: add frontend specific rules to biome config
  packages/dev/biome-config/configs/biome-frontend.jsonc
Labels: patch

#219 http client 204 support
  packages/app/backend-http-client/README.md
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/src/client/constants.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/backend-http-client/src/client/types.ts
Labels: major

#223 Fixing release
  packages/app/backend-http-client/package.json
Labels: major

#224 fix: allow test folder to be nested
  packages/app/backend-http-client/package.json
  packages/dev/biome-config/configs/biome-base.jsonc
Labels: patch

#222 fix: remove globals from frontend biome config
  packages/app/backend-http-client/package.json
  packages/dev/biome-config/configs/biome-frontend.jsonc
Labels: patch

#226 [background-jobs-common] Switch to Biome
  packages/app/background-jobs-common/.eslintignore
  packages/app/background-jobs-common/.eslintrc.json
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/factories/AbstractBullmqFactory.ts
  packages/app/background-jobs-common/src/background-job-processor/factories/CommonBullmqFactory.ts
  packages/app/background-jobs-common/src/background-job-processor/logger/BackgroundJobProcessorLogger.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/logger/BackgroundJobProcessorLogger.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/types.ts
  packages/app/background-jobs-common/src/background-job-processor/types.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
  packages/app/background-jobs-common/src/index.ts
  packages/app/background-jobs-common/test/dependencyMocks.spec.ts
  packages/app/background-jobs-common/test/dependencyMocks.ts
  packages/app/background-jobs-common/test/processors/TestFailingBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestReturnValueBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestStalledBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestSucessBackgroundJobProcessor.ts
  packages/app/background-jobs-common/tsconfig.json
  packages/app/background-jobs-common/tsconfig.lint.json
Labels: skip-release

#225 MET-160 Support for Redis keyPrefix
  packages/app/background-jobs-common/.env.test
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
  packages/app/background-jobs-common/test/dependencyMocks.spec.ts
  packages/app/background-jobs-common/test/dependencyMocks.ts
  packages/app/background-jobs-common/test/processors/TestReturnValueBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestStalledBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/setup.ts
Labels: major

#228 MET-160 Bump node
  packages/app/background-jobs-common/package.json
Labels: major

#229 MET-160 Bump rimraf
  packages/app/background-jobs-common/package.json
Labels: major

#230 MET-160 Fix dist structure
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestFailingBackgroundJobProcessor.ts
  packages/app/background-jobs-common/test/processors/TestSucessBackgroundJobProcessor.ts
  packages/app/background-jobs-common/tsconfig.json
  packages/app/background-jobs-common/vitest.config.mts
Labels: patch

#233 Adding biome.package.json
  packages/app/background-jobs-common/biome.json
  packages/app/background-jobs-common/package.json
  packages/dev/biome-config/README.md
  packages/dev/biome-config/configs/biome-package.jsonc
  packages/dev/biome-config/package.json
Labels: skip-release

#231 prisma-utils -> biome
  packages/app/prisma-utils/.eslintignore
  packages/app/prisma-utils/.eslintrc.json
  packages/app/prisma-utils/biome.json
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/src/cockroachdbError.spec.ts
  packages/app/prisma-utils/src/cockroachdbError.ts
  packages/app/prisma-utils/src/index.ts
  packages/app/prisma-utils/src/prismaError.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/prisma-utils/src/types.ts
  packages/app/prisma-utils/test/DbCleaner.ts
  packages/app/prisma-utils/tsconfig.json
  packages/app/prisma-utils/tsconfig.lint.json
  packages/app/prisma-utils/vite.config.ts
Labels: skip-release

#234 feat: add eslint-config-biome-companion
  packages/dev/eslint-config-biome-companion/README.md
Labels: skip-release

#235 fix: add npm run instructions
  packages/dev/eslint-config-biome-companion/README.md
Labels: skip-release

#236 Fix typo in README
  packages/dev/biome-config/README.md
Labels: skip-release

#237 feat: add uniq utility
  packages/app/universal-ts-utils/biome.json
  packages/app/universal-ts-utils/src/array/unique.spec.ts
  packages/app/universal-ts-utils/src/array/unique.ts
Labels: minor

#238 Update vite-config dependencies
  packages/dev/package-vite-config/.eslintignore
  packages/dev/package-vite-config/.eslintrc.json
  packages/dev/package-vite-config/.prettierignore
  packages/dev/package-vite-config/biome.json
  packages/dev/package-vite-config/package.config.ts
  packages/dev/package-vite-config/package.json
  packages/dev/package-vite-config/tsconfig.json
Labels: major

#242 Pin Node version to a fixed one
  .github/workflows/ci.yml
  packages/dev/package-vite-config/package.json
Labels: skip-release

#241 Turborepo 2
  package.json
  turbo.json
Labels: skip-release

#243 Fixing retries allowed countig
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/test/processors/TestFailingBackgroundJobProcessor.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
Labels: patch

#247 Fixing release actions
  .github/workflows/release.api-common.yml
  .github/workflows/release.backend-http-client.yml
  .github/workflows/release.background-jobs-common.yml
  .github/workflows/release.biome-config.yml
  .github/workflows/release.context-fastify-plugins.yml
  .github/workflows/release.error-utils.yml
  .github/workflows/release.eslint-config.yml
  .github/workflows/release.eslint-package-vite-config.yml
  .github/workflows/release.events-common.yml
  .github/workflows/release.id-utils.yml
  .github/workflows/release.non-translatable-markup.yml
  .github/workflows/release.prettier-config.yml
  .github/workflows/release.prisma-utils.yml
  .github/workflows/release.script-utils.yml
  .github/workflows/release.supported-languages.yml
  .github/workflows/release.universal-ts-utils.yml
  .github/workflows/release.websockets-common.yml
Labels: skip-release

#248 prisma update
  packages/app/prisma-utils/package.json
Labels: minor

#250 Fixing build
  packages/app/api-common/package.json
  packages/app/error-utils/package.json
  packages/app/events-common/package.json
  packages/app/id-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/prisma-utils/package.json
  packages/app/script-utils/package.json
  packages/app/supported-languages/package.json
  packages/app/websockets-common/package.json
Labels: skip-release

#251 Update dependencies
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/vitest.config.mts
Labels: skip-release

#254 vitest update
  packages/app/api-common/package.json
  packages/app/backend-http-client/package.json
  packages/app/context-fastify-plugins/package.json
  packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.spec.ts
  packages/app/error-utils/package.json
  packages/app/events-common/package.json
  packages/app/events-common/vite.config.ts
  packages/app/id-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/vitest.config.mts
  packages/app/script-utils/package.json
  packages/app/supported-languages/package.json
  packages/app/universal-ts-utils/package.json
  packages/app/websockets-common/package.json
Labels: skip-release
