Repository lokalise/shared-ts-libs, pull requests merged in 2024-11, with the labels that each got.

#376 Universal-ts-utils preparing internal utils folder
  packages/app/universal-ts-utils/package.json
  packages/app/universal-ts-utils/src/internal/compare.spec.ts
  packages/app/universal-ts-utils/src/internal/compare.ts
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/array/areStringArraysEqual.spec.ts
  packages/app/universal-ts-utils/src/public/array/areStringArraysEqual.ts
  packages/app/universal-ts-utils/src/public/array/callChunked.spec.ts
  packages/app/universal-ts-utils/src/public/array/callChunked.ts
  packages/app/universal-ts-utils/src/public/array/chunk.spec.ts
  packages/app/universal-ts-utils/src/public/array/chunk.ts
  packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.spec.ts
  packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.ts
  packages/app/universal-ts-utils/src/public/array/removeFalsy.spec.ts
  packages/app/universal-ts-utils/src/public/array/removeFalsy.ts
  packages/app/universal-ts-utils/src/public/array/removeNullish.spec.ts
  packages/app/universal-ts-utils/src/public/array/removeNullish.ts
  packages/app/universal-ts-utils/src/public/array/sort.spec.ts
  packages/app/universal-ts-utils/src/public/array/sort.ts
  packages/app/universal-ts-utils/src/public/array/sortByField.spec.ts
  packages/app/universal-ts-utils/src/public/array/sortByField.ts
  packages/app/universal-ts-utils/src/public/array/unique.spec.ts
  packages/app/universal-ts-utils/src/public/array/unique.ts
  packages/app/universal-ts-utils/src/public/object/areDeepEqual.spec.ts
  packages/app/universal-ts-utils/src/public/object/areDeepEqual.ts
Labels: patch

#377 TS utils group by
  packages/app/universal-ts-utils/src/internal/types.ts
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/array/sortByField.ts
  packages/app/universal-ts-utils/src/public/object/groupBy.spec.ts
  packages/app/universal-ts-utils/src/public/object/groupBy.ts
  packages/app/universal-ts-utils/src/public/object/groupByUnique.spec.ts
  packages/app/universal-ts-utils/src/public/object/groupByUnique.ts
Labels: minor

#378 Trying to fix imports on universal-ts-utils
  packages/app/universal-ts-utils/biome.json
  packages/app/universal-ts-utils/src/internal/compare.spec.ts
  packages/app/universal-ts-utils/src/public/array/areStringArraysEqual.spec.ts
  packages/app/universal-ts-utils/src/public/array/callChunked.spec.ts
  packages/app/universal-ts-utils/src/public/array/chunk.spec.ts
  packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.spec.ts
  packages/app/universal-ts-utils/src/public/array/removeFalsy.spec.ts
  packages/app/universal-ts-utils/src/public/array/removeNullish.spec.ts
  packages/app/universal-ts-utils/src/public/array/sort.spec.ts
  packages/app/universal-ts-utils/src/public/array/sort.ts
  packages/app/universal-ts-utils/src/public/array/sortByField.spec.ts
  packages/app/universal-ts-utils/src/public/array/sortByField.ts
  packages/app/universal-ts-utils/src/public/array/unique.spec.ts
  packages/app/universal-ts-utils/src/public/object/areDeepEqual.spec.ts
  packages/app/universal-ts-utils/src/public/object/groupBy.spec.ts
  packages/app/universal-ts-utils/src/public/object/groupBy.ts
  packages/app/universal-ts-utils/src/public/object/groupByUnique.spec.ts
  packages/app/universal-ts-utils/src/public/object/groupByUnique.ts
Labels: patch

#389 Restrict BullMQ to the latest compatible version
  packages/app/background-jobs-common/package.json
Labels: skip-release

#390 Adjust code to support newer bullmq
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/factories/AbstractBullmqFactory.ts
  packages/app/background-jobs-common/src/background-job-processor/factories/CommonBullmqFactory.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/src/background-job-processor/types.ts
Labels: major
