Repository lokalise/shared-ts-libs, pull requests merged in 2024-10, with the labels that each got.

#349 Biome ESM import rule
  packages/dev/biome-config/configs/biome-esm.jsonc
Labels: minor

#348 Feature/universal ts utils new methods
  packages/app/universal-ts-utils/src/array/areStringArraysEqual.ts
  packages/app/universal-ts-utils/src/array/callChunked.spec.ts
  packages/app/universal-ts-utils/src/array/callChunked.ts
  packages/app/universal-ts-utils/src/array/sort.spec.ts
  packages/app/universal-ts-utils/src/array/sort.ts
  packages/app/universal-ts-utils/src/array/sortByField.spec.ts
  packages/app/universal-ts-utils/src/array/sortByField.ts
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/object/areDeepEqual.spec.ts
  packages/app/universal-ts-utils/src/object/areDeepEqual.ts
Labels: minor

#355 Make plugins compatible with fastify 5
  packages/app/context-fastify-plugins/package.json
  packages/app/context-fastify-plugins/src/plugins/opentelemetry/prismaOtelTracingPlugin.ts
  packages/app/context-fastify-plugins/src/plugins/requestContextProviderPlugin.ts
  packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.ts
Labels: minor

#354 feat(AP-5236): Introduce metrics utils app package
  .github/workflows/release.metrics-utils.yml
  packages/app/metrics-utils/.gitignore
  packages/app/metrics-utils/LICENSE.md
  packages/app/metrics-utils/README.md
  packages/app/metrics-utils/biome.json
  packages/app/metrics-utils/package.json
  packages/app/metrics-utils/src/AbstractCounterMetric.spec.ts
  packages/app/metrics-utils/src/AbstractCounterMetric.ts
  packages/app/metrics-utils/src/index.ts
  packages/app/metrics-utils/tsconfig.json
  packages/app/metrics-utils/tsconfig.lint.json
  packages/app/metrics-utils/vite.config.ts
Labels: major

#353 Updating to node-core 13
  packages/app/backend-http-client/package.json
  packages/app/background-jobs-common/package.json
  packages/app/context-fastify-plugins/package.json
  packages/app/error-utils/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/prisma-utils/package.json
  packages/app/script-utils/package.json
  packages/app/supported-languages/package.json
Labels: minor

#356 prisma-utils triggering release
  packages/app/prisma-utils/package.json
Labels: minor

#357 Triggering release on script-utils
  packages/app/script-utils/package.json
Labels: minor

#358 context-fastify-plugins triggering release
  packages/app/context-fastify-plugins/package.json
Labels: minor

#362 Update dependencies
  packages/app/api-common/package.json
  packages/app/backend-http-client/package.json
  packages/app/background-jobs-common/package.json
  packages/app/context-fastify-plugins/package.json
  packages/app/error-utils/package.json
  packages/app/events-common/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/id-utils/package.json
  packages/app/metrics-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/prisma-utils/.prettierignore
  packages/app/prisma-utils/package.json
  packages/app/script-utils/package.json
  packages/app/supported-languages/package.json
  packages/app/universal-ts-utils/package.json
  packages/app/websockets-common/package.json
  packages/dev/biome-config/package.json
  packages/dev/package-vite-config/package.json
Labels: skip-release

#360 healthcheck release
  packages/app/healthcheck-utils/package.json
Labels: minor

#361 supported-languages release
  packages/app/supported-languages/package.json
Labels: minor

#363 be http client triggering release
  packages/app/backend-http-client/package.json
Labels: minor

#364 Fixing be-http-client release
  packages/app/backend-http-client/package.json
Labels: minor

#365 Support newer BullMQ versions
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/types.ts
Labels: major

#366 Move fastify-extras to be a peer dependency
  packages/app/metrics-utils/package.json
Labels: major

#373 AP-5778 introduce prisma metrics plugin
  packages/app/prisma-utils/README.md
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/prisma/schema.prisma
  packages/app/prisma-utils/src/index.ts
  packages/app/prisma-utils/src/plugins/CollectionScheduler.ts
  packages/app/prisma-utils/src/plugins/MetricsCollector.ts
  packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.spec.ts
  packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.ts
  packages/app/prisma-utils/src/prismaClientFactory.spec.ts
Labels: minor

#374 AP-5778 prisma metrics plugin
  packages/app/prisma-utils/src/plugins/CollectionScheduler.ts
  packages/app/prisma-utils/src/plugins/MetricsCollector.ts
  packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.ts
Labels: patch
