Repository lokalise/shared-ts-libs, pull requests merged in 2024-05, with the labels that each got.

#144 Update documentation
  packages/app/background-jobs-common/README.md
Labels: patch

#145 Extract backend-http-client from node-core
  .github/workflows/release.backend-http-client.yml
  package.json
  packages/app/backend-http-client/.eslintignore
  packages/app/backend-http-client/.eslintrc.json
  packages/app/backend-http-client/.gitignore
  packages/app/backend-http-client/.npmignore
  packages/app/backend-http-client/LICENSE.md
  packages/app/backend-http-client/README.md
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/httpClient.spec.ts
  packages/app/backend-http-client/src/httpClient.ts
  packages/app/backend-http-client/src/mock-data/mockProduct1.json
  packages/app/backend-http-client/src/mock-data/mockProductsLimit3.json
  packages/app/backend-http-client/tsconfig.json
  packages/app/backend-http-client/tsconfig.lint.json
  packages/app/backend-http-client/vitest.config.mts
Labels: skip-release

#147 Enforce stricter constraints on HTTP client params
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/httpClient.spec.ts
  packages/app/backend-http-client/src/httpClient.ts
  packages/app/backend-http-client/tsconfig.json
  packages/app/backend-http-client/vitest.config.mts
Labels: major

#151 feat(AP-3587): add optional languageId to CM WS event schema
  packages/app/websockets-common/src/rooms.ts
Labels: minor

#152 Crdb transaction retry
  packages/app/prisma-utils/src/cockroachdbError.spec.ts
  packages/app/prisma-utils/src/cockroachdbError.ts
  packages/app/prisma-utils/src/index.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/prisma-utils/src/types.ts
  packages/app/prisma-utils/vitest.config.mts
Labels: bug, patch

#153 clean logs on success
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: minor

#154 chore(background-jobs-common): extract start and finish logs to dedicated methods
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: minor

#156 Bugsnag report error details
  packages/app/error-utils/src/bugsnag.spec.ts
  packages/app/error-utils/src/bugsnag.ts
  packages/app/error-utils/src/index.spec.ts
Labels: minor

#155 Prisma transaction retry delay
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/prisma-utils/src/types.ts
Labels: minor
