Repository lokalise/shared-ts-libs, pull requests merged in 2025-01, with the labels that each got.

#429 feat(universal-ts-utils): add nonEmptyArray utils
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/array/defineNonEmptyArray.spec.ts
  packages/app/universal-ts-utils/src/public/array/defineNonEmptyArray.ts
  packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.ts
  packages/app/universal-ts-utils/src/public/array/mapNonEmptyArray.spec.ts
  packages/app/universal-ts-utils/src/public/array/mapNonEmptyArray.ts
  packages/app/universal-ts-utils/src/public/array/nonEmptyArray.ts
Labels: minor

#442 Support TSX for ESM rule
  packages/dev/biome-config/configs/biome-esm.jsonc
Labels: minor

#444 Use correct extension for components
  packages/dev/biome-config/configs/biome-esm.jsonc
  packages/dev/biome-config/package.json
Labels: patch

#443 improve exports config for universal ts utils
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/package.json
Labels: major

#446 chore: Update CODEOWNERS
  CODEOWNERS
Labels: skip-release

#448 feature: introduce new param to improve discoverability of autorun opt
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/constants.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/test/processors/TestSuccessBackgroundJobProcessor.ts
Labels: major
