Repository lokalise/shared-ts-libs, pull requests merged in 2025-03, with the labels that each got.

#505 bg processor shared spy instance
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.barrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.error.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.repeatable.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.stalled.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.success.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/test/TestDependencyFactory.ts
  packages/app/background-jobs-common/test/processors/TestBarrierBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/test/processors/TestFailingBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/test/processors/TestOverrideProcessBackgroundProcessor.ts
  packages/app/background-jobs-common/test/processors/TestReturnValueBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/test/processors/TestStalledBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/test/processors/TestSuccessBackgroundJobProcessorNew.ts
Labels: major

#506 Browser compatible cursor encoding
  packages/app/api-common/src/cursorCodec.ts
  packages/app/api-common/src/index.ts
  packages/app/api-common/test/cursorCodec.spec.ts
  packages/app/api-common/vite.config.ts
Labels: minor

#503 adjust NT tags regex
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.spec.ts
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.ts
  packages/app/non-translatable-markup/src/methods/utils.ts
Labels: minor

#511 Updating opentelemetry deps
  packages/app/context-fastify-plugins/package.json
Labels: patch

#512 package-vite-config vitest 3
  packages/dev/package-vite-config/package.config.ts
  packages/dev/package-vite-config/package.json
Labels: patch

#513 * adjust removeNonTranslatableTags logic
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.spec.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.spec.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.spec.ts
  packages/app/non-translatable-markup/src/methods/utils.ts
Labels: patch

#514 Chore/vite 6
  packages/app/api-common/package.json
  packages/app/background-jobs-common/package.json
  packages/app/error-utils/package.json
  packages/app/events-common/package.json
  packages/app/fastify-api-contracts/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/id-utils/package.json
  packages/app/metrics-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/script-utils/package.json
  packages/app/websockets-common/package.json
  packages/dev/package-vite-config/package.json
Labels: skip-release

#518 Chore/package vite config release
  packages/app/api-common/package.json
  packages/app/background-jobs-common/package.json
  packages/app/error-utils/package.json
  packages/app/events-common/package.json
  packages/app/fastify-api-contracts/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/id-utils/package.json
  packages/app/metrics-utils/package.json
  packages/app/non-translatable-markup/package.json
  packages/app/script-utils/package.json
  packages/app/websockets-common/package.json
  packages/dev/package-vite-config/package.json
Labels: skip-release

#517 Group OTel dependencies
  .github/dependabot.yml
Labels: skip-release

#520 migrate non-translatable-markup to ESM
  packages/app/non-translatable-markup/biome.json
  packages/app/non-translatable-markup/package.json
  packages/app/non-translatable-markup/src/index.ts
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.spec.ts
  packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.spec.ts
  packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
  packages/app/non-translatable-markup/src/methods/isTextTranslatable.ts
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.spec.ts
  packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.ts
  packages/app/non-translatable-markup/src/methods/utils.ts
  packages/app/non-translatable-markup/tsconfig.build.json
  packages/app/non-translatable-markup/tsconfig.json
  packages/app/non-translatable-markup/tsconfig.lint.json
  packages/app/non-translatable-markup/vite.config.ts
  packages/app/non-translatable-markup/vitest.config.ts
Labels: major

#521 minor: we need to trigger an npm publish and we don't have any methods, hence removing the comment
  packages/app/frontend-http-client/src/client.ts
Labels: minor

#522 fix(frontend-http-client): build with turborepo
  packages/app/frontend-http-client/package.json
Labels: patch

#526 feat: Support API contracts for payload requests in backend-http-client
  packages/app/backend-http-client/README.md
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/apiContractTypes.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/backend-http-client/tsconfig.json
Labels: minor

#527 docs: Add documentation for handler/route separation
  packages/app/fastify-api-contracts/README.md
Labels: patch

#523 chore: add sharable tsconfig package
  .github/workflows/release.tsconfig.yml
  packages/app/non-translatable-markup/package.json
  packages/app/non-translatable-markup/tsconfig.build.json
  packages/app/non-translatable-markup/tsconfig.json
  packages/app/non-translatable-markup/vitest.config.ts
  packages/dev/tsconfig/LICENSE.md
  packages/dev/tsconfig/README.md
  packages/dev/tsconfig/configs/base.json
  packages/dev/tsconfig/configs/build-app.json
  packages/dev/tsconfig/configs/build-private-lib.json
  packages/dev/tsconfig/configs/build-public-lib.json
  packages/dev/tsconfig/configs/bundler-dom.json
  packages/dev/tsconfig/configs/bundler.json
  packages/dev/tsconfig/configs/tsc-dom.json
  packages/dev/tsconfig/configs/tsc.json
  packages/dev/tsconfig/package.json
Labels: patch

#530 Chore/fastify contract common tsconfig
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/types.ts
  packages/app/fastify-api-contracts/tsconfig.build.json
  packages/app/fastify-api-contracts/tsconfig.json
  packages/app/fastify-api-contracts/vitest.config.mts
Labels: patch

#533 Chore/api common ts config
  packages/app/api-common/biome.json
  packages/app/api-common/package.json
  packages/app/api-common/src/apiSchemas.spec.ts
  packages/app/api-common/src/apiSchemas.ts
  packages/app/api-common/src/cursorCodec.spec.ts
  packages/app/api-common/src/cursorCodec.ts
  packages/app/api-common/src/index.ts
  packages/app/api-common/src/paginationUtils.spec.ts
  packages/app/api-common/src/paginationUtils.ts
  packages/app/api-common/src/typeUtils.ts
  packages/app/api-common/test/typeUtils.spec.ts
  packages/app/api-common/tsconfig.build.json
  packages/app/api-common/tsconfig.json
  packages/app/api-common/tsconfig.lint.json
  packages/app/api-common/vite.config.ts
Labels: major

#534 Fix id-utils exports
  packages/app/id-utils/package.json
Labels: skip-release

#535 Chore/context fastify plugins common tsconfig
  packages/app/context-fastify-plugins/biome.json
  packages/app/context-fastify-plugins/package.json
  packages/app/context-fastify-plugins/src/index.ts
  packages/app/context-fastify-plugins/src/plugins/opentelemetry/prismaOtelTracingPlugin.ts
  packages/app/context-fastify-plugins/src/plugins/opentelemetry/spanProcessors.ts
  packages/app/context-fastify-plugins/src/plugins/requestContextProviderPlugin.spec.ts
  packages/app/context-fastify-plugins/src/plugins/requestContextProviderPluginTypes.spec.ts
  packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.spec.ts
  packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.ts
  packages/app/context-fastify-plugins/tsconfig.build.json
  packages/app/context-fastify-plugins/tsconfig.json
  packages/app/context-fastify-plugins/tsconfig.lint.json
Labels: major

#536 Removing not needed noEmit
  packages/app/api-common/package.json
  packages/app/backend-http-client/package.json
  packages/app/fastify-api-contracts/package.json
  packages/app/id-utils/package.json
  packages/app/universal-ts-utils/package.json
Labels: skip-release

#539 feat: Add DELETE and GET route support and more tests
  packages/app/backend-http-client/README.md
  packages/app/backend-http-client/index.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/backend-http-client/vitest.config.mts
Labels: minor

#540 Chore/prisma utils common tsconfig
  packages/app/prisma-utils/biome.json
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/src/errors/cockroachdbError.spec.ts
  packages/app/prisma-utils/src/errors/index.ts
  packages/app/prisma-utils/src/index.ts
  packages/app/prisma-utils/src/plugins/MetricsCollector.ts
  packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.spec.ts
  packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.ts
  packages/app/prisma-utils/src/prismaClientFactory.spec.ts
  packages/app/prisma-utils/src/prismaClientFactory.ts
  packages/app/prisma-utils/src/prismaTransaction.isolationLevel.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/prisma-utils/src/types.ts
  packages/app/prisma-utils/test/DbCleaner.ts
  packages/app/prisma-utils/tsconfig.build.json
  packages/app/prisma-utils/tsconfig.json
  packages/app/prisma-utils/tsconfig.lint.json
Labels: major

#541 Fixing index issue for be-http-client
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/index.ts
  packages/app/backend-http-client/vitest.config.mts
Labels: patch

#542 Trying to fix tests
  packages/app/prisma-utils/package.json
Labels: skip-release

#538 Chore/error utils common tsconfig
  packages/app/error-utils/biome.json
  packages/app/error-utils/package.json
  packages/app/error-utils/src/bugsnag.spec.ts
  packages/app/error-utils/src/bugsnag.ts
  packages/app/error-utils/src/index.ts
  packages/app/error-utils/tsconfig.build.json
  packages/app/error-utils/tsconfig.json
  packages/app/error-utils/tsconfig.lint.json
Labels: major

#544 chore: metrics-utils common tsconfig
  packages/app/metrics-utils/biome.json
  packages/app/metrics-utils/package.json
  packages/app/metrics-utils/src/AbstractCounterMetric.spec.ts
  packages/app/metrics-utils/src/index.ts
  packages/app/metrics-utils/tsconfig.build.json
  packages/app/metrics-utils/tsconfig.json
  packages/app/metrics-utils/tsconfig.lint.json
  packages/app/metrics-utils/vite.config.ts
Labels: major

#545 Chore: events-common shared tsconfig
  packages/app/events-common/biome.json
  packages/app/events-common/package.json
  packages/app/events-common/src/index.ts
  packages/app/events-common/test/baseEventSchemas.spec.ts
  packages/app/events-common/tsconfig.build.json
  packages/app/events-common/tsconfig.json
  packages/app/events-common/tsconfig.lint.json
  packages/app/events-common/vite.config.ts
  packages/app/events-common/vitest.config.ts
Labels: major

#547 Chore/healthcheck utils common tsconfig
  packages/app/healthcheck-utils/biome.json
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
  packages/app/healthcheck-utils/src/healthchecks.ts
  packages/app/healthcheck-utils/src/index.ts
  packages/app/healthcheck-utils/tsconfig.build.json
  packages/app/healthcheck-utils/tsconfig.json
  packages/app/healthcheck-utils/tsconfig.lint.json
  packages/app/healthcheck-utils/vitest.config.mts
Labels: major

#548 chore: script-utils using shared tsconfig
  packages/app/script-utils/biome.json
  packages/app/script-utils/package.json
  packages/app/script-utils/src/index.ts
  packages/app/script-utils/src/vault/syncEnvWithVault.spec.ts
  packages/app/script-utils/src/vault/syncEnvWithVault.ts
  packages/app/script-utils/tsconfig.build.json
  packages/app/script-utils/tsconfig.json
  packages/app/script-utils/tsconfig.lint.json
  packages/app/script-utils/vite.config.ts
Labels: major

#550 Chore/websockets common common tsconfig
  packages/app/websockets-common/biome.json
  packages/app/websockets-common/package.json
  packages/app/websockets-common/src/events/client-to-server/index.ts
  packages/app/websockets-common/src/events/client-to-server/reservedRoomEvents.ts
  packages/app/websockets-common/src/events/index.ts
  packages/app/websockets-common/src/events/server-to-client/index.ts
  packages/app/websockets-common/src/events/server-to-client/reservedRoomEvents.ts
  packages/app/websockets-common/src/index.ts
  packages/app/websockets-common/src/types/index.ts
  packages/app/websockets-common/test/rooms.test.ts
  packages/app/websockets-common/tsconfig.build.json
  packages/app/websockets-common/tsconfig.json
  packages/app/websockets-common/tsconfig.lint.json
  packages/app/websockets-common/vite.config.ts
Labels: major

#551 Adding missing export + refactoring exports for simplicity
  packages/app/background-jobs-common/src/background-job-processor/factories/index.ts
  packages/app/background-jobs-common/src/background-job-processor/index.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/index.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/index.ts
Labels: patch

#546 Chore: FE http client common tsconfig
  packages/app/frontend-http-client/biome.json
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/src/index.ts
  packages/app/frontend-http-client/src/utils/bodyUtils.ts
  packages/app/frontend-http-client/tsconfig.build.json
  packages/app/frontend-http-client/tsconfig.json
  packages/app/frontend-http-client/tsup.config.ts
  packages/app/frontend-http-client/vitest.config.ts
Labels: major

#543 Trying to fix flaky test
  packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.spec.ts
Labels: skip-release

#554 Chore: Common biome config
  biome.json
  packages/app/api-common/biome.json
  packages/app/backend-http-client/biome.json
  packages/app/background-jobs-common/biome.json
  packages/app/context-fastify-plugins/biome.json
  packages/app/error-utils/biome.json
  packages/app/events-common/biome.json
  packages/app/fastify-api-contracts/biome.json
  packages/app/frontend-http-client/biome.json
  packages/app/healthcheck-utils/biome.json
  packages/app/id-utils/biome.json
  packages/app/metrics-utils/biome.json
  packages/app/non-translatable-markup/biome.json
  packages/app/prisma-utils/biome.json
  packages/app/script-utils/biome.json
  packages/app/supported-languages/biome.json
  packages/app/universal-ts-utils/biome.json
  packages/app/websockets-common/biome.json
  packages/dev/package-vite-config/biome.json
Labels: skip-release

#555 chore: enable ts extension usage
  packages/dev/tsconfig/configs/base.json
  packages/dev/tsconfig/configs/build-app.json
Labels: minor

#559 fix: Accept any fastify instance
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
Labels: patch

#560 redis-semaphore 5.6.2
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/tsconfig.json
  packages/app/healthcheck-utils/tsconfig.json
Labels: skip-release

#556 AP-6426 added `sendPostWithProgress()` util function
  packages/app/frontend-http-client/README.md
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/src/client.spec.ts
  packages/app/frontend-http-client/src/client.ts
  packages/app/frontend-http-client/src/index.ts
  packages/app/frontend-http-client/src/utils/bodyUtils.ts
  packages/app/frontend-http-client/src/utils/errorUtils.ts
  packages/app/frontend-http-client/tsconfig.json
Labels: minor

#563 Move api contracts to its own package
  .github/workflows/release.api-contracts.yml
  packages/app/api-contracts/.gitignore
  packages/app/api-contracts/LICENSE.md
  packages/app/api-contracts/README.md
  packages/app/api-contracts/package.json
  packages/app/api-contracts/src/HttpStatusCodes.ts
  packages/app/api-contracts/src/__snapshots__/apiContracts.spec.ts.snap
  packages/app/api-contracts/src/apiContracts.metadata.spec.ts
  packages/app/api-contracts/src/apiContracts.spec.ts
  packages/app/api-contracts/src/apiContracts.ts
  packages/app/api-contracts/tsconfig.build.json
  packages/app/api-contracts/tsconfig.json
  packages/app/api-contracts/vitest.config.ts
Labels: minor

#564 Switch to consume api-contracts lib
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.metadataMapper.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
  packages/app/fastify-api-contracts/src/index.ts
  packages/app/fastify-api-contracts/src/types.ts
Labels: major

#565 docs: Fix documentation for api contract module augmentation
  packages/app/api-contracts/README.md
Labels: patch

#566 Switch fe-client to api-contracts
  packages/app/frontend-http-client/README.md
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/src/client.spec.ts
  packages/app/frontend-http-client/src/client.ts
Labels: major

#567 Migrate be client to api contracts lib
  packages/app/backend-http-client/README.md
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/apiContractTypes.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
Labels: major

#562 objectValues type
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/type/ObjectValues.spec.ts
  packages/app/universal-ts-utils/src/public/type/ObjectValues.ts
Labels: minor

#568 Feature/queue id getter
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
Labels: minor
