Repository lokalise/shared-ts-libs, pull requests merged in 2025-05, with the labels that each got.

#612 feat: Expose asyncRegister for periodic jobs
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts
  packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
  packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
Labels: minor

#613 Remove staleness parameter, we always depend on the data available
  packages/app/healthcheck-utils/README.md
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
Labels: javascript, major

#617 bull queues grouping
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/constants.ts
  packages/app/background-jobs-common/src/background-job-processor/errors/MutedUnrecoverableError.ts
  packages/app/background-jobs-common/src/background-job-processor/errors/utils.ts
  packages/app/background-jobs-common/src/background-job-processor/index.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/backgroundJobProcessorGetActiveQueueIds.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.error.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/commonBullDashboardGroupingBuilder.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/commonBullDashboardGroupingBuilder.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/constants.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/createSanitizedRedisClient.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/index.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/sanitizeRedisConfig.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
  packages/app/background-jobs-common/src/index.ts
  packages/app/background-jobs-common/test/processors/TestBasicBackgroundJobProcessor.ts
Labels: minor

#619 Active queue ids issue
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/registerActiveQueueIds.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/registerActiveQueueIds.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
Labels: bug, patch

#621 Narrowing down queue config type
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
Labels: patch

#622 Adding resolved queue id getter to old processor
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Labels: patch

#620 chore: Add Node 24
  .github/workflows/ci.yml
Labels: skip-release

#623 EXP-438 sqs queue names and prefix length validation
  packages/app/aws-config/README.md
  packages/app/aws-config/src/awsConfig.spec.ts
  packages/app/aws-config/src/awsConfig.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsResolver.spec.ts
Labels: minor

#624 node-core 14 on bj-jobs-common
  packages/app/background-jobs-common/package.json
Labels: patch

#625 context-fastify-plugin -> node-core 14
  packages/app/context-fastify-plugins/package.json
Labels: patch

#626 healtchech-utils node-core 14
  packages/app/healthcheck-utils/package.json
Labels: patch

#627 prisma-utils node-core 14
  packages/app/prisma-utils/package.json
Labels: patch

#628 script-utils node-core 14
  packages/app/script-utils/package.json
Labels: patch

#629 Dev dependencies updated
  packages/app/aws-config/package.json
  packages/app/backend-http-client/package.json
  packages/app/error-utils/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/supported-languages/package.json
Labels: skip-release

#631 * change queue name validation logic
  packages/app/aws-config/src/message-queue-toolkit/utils.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/utils.ts
Labels: minor

#633 Make prisma-utils CI more predictable by pinning dependency
  packages/app/prisma-utils/package.json
Labels: skip-release

#634 Update zod for backend-http-client
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/apiContractTypes.ts
  packages/app/backend-http-client/src/client/constants.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/backend-http-client/src/client/types.ts
  packages/app/frontend-http-client/src/client.spec.ts
Labels: skip-release

#630 AP-7179 allow passing custom callback to `MswHelper`
  packages/app/universal-testing-utils/README.md
  packages/app/universal-testing-utils/src/MswHelper.spec.ts
  packages/app/universal-testing-utils/src/MswHelper.ts
  packages/app/universal-testing-utils/test/testContracts.ts
Labels: minor

#637 Add option to set job options as a function
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
Labels: minor

#638 Fixing the job options callback type
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
Labels: patch

#639 Feature: processor payload validation
  packages/app/background-jobs-common/src/background-job-processor/errors/MutedUnrecoverableError.ts
  packages/app/background-jobs-common/src/background-job-processor/errors/ZodUnrecoverableError.ts
  packages/app/background-jobs-common/src/background-job-processor/errors/utils.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.error.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
Labels: minor
