Repository lokalise/shared-ts-libs, pull requests merged in 2025-02, with the labels that each got.

#449 feat: add uniqueByProperty array utility function
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/array/uniqueByProperty.spec.ts
  packages/app/universal-ts-utils/src/public/array/uniqueByProperty.ts
Labels: minor

#447 Adding types: FreeFormRecord, MayOmit and MakeRequired
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/type/FreeformRecord.spec.ts
  packages/app/universal-ts-utils/src/public/type/FreeformRecord.ts
  packages/app/universal-ts-utils/src/public/type/MakeRequired.spec.ts
  packages/app/universal-ts-utils/src/public/type/MakeRequired.ts
  packages/app/universal-ts-utils/src/public/type/MayOmit.spec.ts
  packages/app/universal-ts-utils/src/public/type/MayOmit.ts
Labels: minor

#452 feat: type-safe queueManager
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/managers/FakeQueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/JobRegistry.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
Labels: major

#453 Worker queue split type improvement
  packages/app/background-jobs-common/src/background-job-processor/managers/FakeQueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/JobRegistry.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/JobRegistry.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractUpdatedBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractUpdatedBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeUpdatedBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/types.ts
Labels: skip-release

#455 Feature/bg split new method signature
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.spec.ts
Labels: skip-release

#456 Feature/queue manager pro version support
  packages/app/background-jobs-common/src/background-job-processor/index.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/FakeQueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/JobRegistry.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/JobRegistry.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.barrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
Labels: skip-release

#462 Feature/get queue registry
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
Labels: minor

#463 bg-common ts-config fix + improving tests
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/barrier/JobQueueSizeThrottlingBarrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/backgroundJobProcessorGetActiveQueueIds.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.barrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.barrier.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.error.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.repeatable.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.spy.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.stalled.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.success.spec.ts
  packages/app/background-jobs-common/test/TestDependencyFactory.spec.ts
  packages/app/background-jobs-common/test/TestDependencyFactory.ts
  packages/app/background-jobs-common/tsconfig.build.json
  packages/app/background-jobs-common/tsconfig.json
  packages/app/background-jobs-common/tsconfig.lint.json
Labels: skip-release

#464 Fix fake processor deps
  packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessorNew.ts
Labels: patch

#465 Improving queue manager type
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.ts
Labels: patch

#467 fix: Update QueueManager.ts start args
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
Labels: patch

#468 feat: move frontend http client
  .github/workflows/release.frontend-http-client.yml
  packages/app/backend-http-client/package.json
  packages/app/frontend-http-client/.gitignore
  packages/app/frontend-http-client/CODE_OF_CONDUCT.md
  packages/app/frontend-http-client/CONTRIBUTING.md
  packages/app/frontend-http-client/LICENSE
  packages/app/frontend-http-client/README.md
  packages/app/frontend-http-client/index.ts
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/src/client.spec.ts
  packages/app/frontend-http-client/src/client.ts
  packages/app/frontend-http-client/src/types.ts
  packages/app/frontend-http-client/src/utils/bodyUtils.ts
  packages/app/frontend-http-client/src/utils/either.ts
  packages/app/frontend-http-client/src/utils/errorUtils.ts
  packages/app/frontend-http-client/src/utils/queryUtils.ts
  packages/app/frontend-http-client/tsconfig.build.json
  packages/app/frontend-http-client/tsconfig.json
  packages/app/frontend-http-client/tsconfig.lint.json
  packages/app/frontend-http-client/tsup.config.ts
  packages/app/frontend-http-client/vitest.config.ts
Labels: minor

#469 Resolve path from route definition
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.spec.ts
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: minor

#471 Simplify types and add description
  packages/app/universal-ts-utils/src/public/api-contracts/__snapshots__/apiContracts.spec.ts.snap
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.spec.ts
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: minor

#475 Fix method generic
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: patch

#470 feat: support API contracts in fastify
  packages/app/fastify-api-contracts/.gitignore
  packages/app/fastify-api-contracts/LICENSE.md
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
  packages/app/fastify-api-contracts/src/index.ts
  packages/app/fastify-api-contracts/tsconfig.build.json
  packages/app/fastify-api-contracts/tsconfig.json
  packages/app/fastify-api-contracts/vite.config.ts
Labels: minor

#477 Add more any
  packages/app/prisma-utils/package.json
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: patch

#476 queue manager allow zod default
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
Labels: minor

#478 feat: support remaining HTTP methods for fastify api contracts
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
  packages/app/fastify-api-contracts/src/index.ts
Labels: major

#484 Document fastify-api-contracts usage
  .github/workflows/release.fastify-api-contracts.yml
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/frontend-http-client/package.json
  packages/app/universal-ts-utils/README.md
Labels: minor

#485 Fixing responseSchemasByStatusCode expected schema
  packages/app/universal-ts-utils/src/public/api-contracts/__snapshots__/apiContracts.spec.ts.snap
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.spec.ts
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: patch

#482 Prisma tests fixes
  packages/app/prisma-utils/package.json
  packages/app/prisma-utils/src/errors/cockroachdbError.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.isolationLevel.spec.ts
  packages/app/prisma-utils/src/prismaTransaction.spec.ts
Labels: patch

#486 Trying to fix issue by using default exports
  packages/app/fastify-api-contracts/package.json
Labels: patch

#487 Remove CJS support
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/vite.config.ts
Labels: patch

#488 Enforce ESM imports
  packages/app/fastify-api-contracts/biome.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/index.ts
Labels: patch

#489 Support header factory
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
Labels: minor

#491 Contract metadata mapper
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.metadataMapper.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/index.ts
  packages/app/fastify-api-contracts/src/types.ts
Labels: minor

#493 Type inference improvement
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: patch

#492 Fastify api contracts type improvements
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
Labels: minor

#480 EXP-128 queue manager deduplication id builder
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.deduplication.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
Labels: minor

#495 Added support for isNonJSONResponseExpected and isEmptyResponseExpected in fastify api contracts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: patch

#496 Fixing issues with deduplication ttl type and delayed jobs in test mode
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.deduplication.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
  packages/app/background-jobs-common/test/TestDependencyFactory.ts
Labels: patch

#499 backoff delay as 1 for tests
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
Labels: patch
