Repository lokalise/shared-ts-libs, pull requests merged in 2025-10, with the labels that each got.

#753 Import fixes
  packages/app/auth/src/fastify/createAuthenticationPreHandler.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.response-types.spec.ts
  packages/app/fastify-bullboard-plugin/src/basicAuth.spec.ts
  packages/app/fastify-bullboard-plugin/src/bullBoard.spec.ts
  packages/app/fastify-bullboard-plugin/src/errorReporterPlugin.spec.ts
  packages/app/fastify-bullboard-plugin/src/index.ts
  packages/app/universal-ts-utils/src/public/type/assertIsNever.test.ts
Labels: skip-release

#752 feat: universal-ts-utils is promise finished
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/promise/promiseWithTimeout.spec.ts
  packages/app/universal-ts-utils/src/public/promise/promiseWithTimeout.ts
Labels: minor

#757 Support pino 10
  packages/app/auth/package.json
  packages/app/background-jobs-common/package.json
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
  packages/app/context-fastify-plugins/package.json
Labels: patch
