Repository lokalise/shared-ts-libs, pull requests merged in 2025-09, with the labels that each got.

#727 feat: support union types on responses
  packages/app/api-contracts/package.json
  packages/app/api-contracts/src/apiContracts.ts
  packages/app/api-contracts/vitest.config.ts
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.response-types.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/src/client.ts
  packages/app/universal-testing-utils/package.json
  packages/app/universal-testing-utils/src/MockttpHelper.spec.ts
  packages/app/universal-testing-utils/src/MockttpHelper.ts
  packages/app/universal-testing-utils/src/MswHelper.spec.ts
  packages/app/universal-testing-utils/src/MswHelper.ts
  packages/app/universal-testing-utils/vitest.config.ts
Labels: minor

#725 Feature: MET-1038 Aws config command support
  packages/app/aws-config/README.md
  packages/app/aws-config/src/event-routing/eventRoutingConfig.spec.ts
  packages/app/aws-config/src/event-routing/eventRoutingConfig.ts
  packages/app/aws-config/src/index.ts
  packages/app/aws-config/src/message-queue-toolkit/AbstractMessageQueueToolkitOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsResolver.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSqsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSqsResolver.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/constants.ts
  packages/app/aws-config/src/message-queue-toolkit/index.ts
  packages/app/aws-config/src/message-queue-toolkit/prehandlers/createRequestContextPreHandler.ts
  packages/app/aws-config/src/message-queue-toolkit/types.ts
Labels: major

#730 Add helper util for generating route description
  packages/app/api-contracts/src/apiContracts.spec.ts
  packages/app/api-contracts/src/apiContracts.ts
Labels: minor

#734 Adding queue policy for SQS
  packages/app/aws-config/src/message-queue-toolkit/AbstractMessageQueueToolkitOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSqsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSqsResolver.spec.ts
Labels: patch

#739 Bugfix/sqs policy config
  packages/app/aws-config/package.json
  packages/app/aws-config/src/message-queue-toolkit/AbstractMessageQueueToolkitOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSqsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSqsResolver.spec.ts
Labels: patch

#743 Add support for testing error cases for mockttphelper
  packages/app/universal-testing-utils/README.md
  packages/app/universal-testing-utils/src/MockttpHelper.spec.ts
  packages/app/universal-testing-utils/src/MockttpHelper.ts
Labels: minor

#744 feat: Collect from iterable utility
  packages/app/universal-ts-utils/README.md
  packages/app/universal-ts-utils/src/node.ts
  packages/app/universal-ts-utils/src/public/iterable/collectFromIterable.spec.ts
  packages/app/universal-ts-utils/src/public/iterable/collectFromIterable.ts
Labels: minor

#746 chore: bump peer fastify-extras in aws-config
  packages/app/aws-config/package.json
Labels: major

#745 EXP-823 use path prefix with api contracts
  packages/app/api-contracts/package.json
  packages/app/api-contracts/src/apiContracts.ts
  packages/app/api-contracts/src/index.ts
  packages/app/api-contracts/src/pathUtils.spec.ts
  packages/app/api-contracts/src/pathUtils.ts
  packages/app/backend-http-client/README.md
  packages/app/backend-http-client/src/client/apiContractTypes.ts
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/frontend-http-client/README.md
  packages/app/frontend-http-client/src/client.spec.ts
  packages/app/frontend-http-client/src/client.ts
  packages/app/frontend-http-client/src/types.ts
Labels: minor
