Repository lokalise/shared-ts-libs, pull requests merged in 2025-08, with the labels that each got.

#699 Fix skiplist logic
  packages/app/fastify-bullboard-plugin/src/basicAuth.ts
Labels: patch

#702 Feature/bull board key prefix fix
  packages/app/fastify-bullboard-plugin/src/bullBoard.spec.ts
  packages/app/fastify-bullboard-plugin/src/bullBoard.ts
  packages/app/fastify-bullboard-plugin/vitest.config.ts
Labels: major

#701 Always using key prefix in bullMq
  packages/app/background-jobs-common/src/background-job-processor/barrier/JobQueueSizeThrottlingBarrierNew.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/barrier/JobQueueSizeThrottlingBarrierNew.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/backgroundJobProcessorGetActiveQueueIds.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/registerActiveQueueIds.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/createSanitizedRedisClient.ts
  packages/app/background-jobs-common/src/background-job-processor/public-utils/index.ts
  packages/app/background-jobs-common/test/TestRedis.ts
  packages/app/background-jobs-common/test/processors/barrier/TestQueueSizeJobBarrierBackgroundJobProcessorNew.ts
  packages/app/prisma-utils/package.json
Labels: major

#707 Remove zod dependency, update deps
  packages/app/universal-ts-utils/package.json
  packages/app/universal-ts-utils/src/public/array/chunk.ts
  packages/app/universal-ts-utils/src/public/waitAndRetry.ts
Labels: patch

#710 Fixing pino import
  packages/app/fastify-bullboard-plugin/src/errorReporterPlugin.ts
Labels: patch

#711 Lint fix in aws-config
  packages/app/aws-config/tests/FakeLogger.ts
Labels: skip-release

#709 Fixing type issue in bg-jobs-common
  packages/app/background-jobs-common/src/background-job-processor/logger/BackgroundJobProcessorLogger.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/logger/BackgroundJobProcessorLogger.ts
Labels: patch

#708 Dev deps update
  packages/app/aws-config/package.json
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/src/client/constants.ts
  packages/app/backend-http-client/src/client/types.ts
  packages/app/backend-http-client/src/errors/ResponseStatusError.ts
  packages/app/fastify-bullboard-plugin/package.json
  packages/app/healthcheck-utils/package.json
  packages/app/universal-testing-utils/package.json
Labels: skip-release

#721 Make releases sequential and use local workflow definition
  .github/workflows/release.yml
  packages/app/api-common/src/apiSchemas.spec.ts
  packages/app/api-common/src/paginationUtils.ts
  packages/app/api-contracts/src/__snapshots__/apiContracts.spec.ts.snap
  packages/app/backend-http-client/src/client/httpClient.spec.ts
  packages/app/backend-http-client/src/client/httpClient.ts
  packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
  packages/app/background-jobs-common/src/background-job-processor/monitoring/registerActiveQueueIds.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.ts
  packages/app/background-jobs-common/test/processors/TestQueueSizeJobBarrierBackgroundJobProcessor.ts
  packages/app/fastify-bullboard-plugin/src/bullBoard.ts
  packages/app/prisma-utils/src/prismaTransaction.ts
  packages/app/universal-ts-utils/src/public/object/areDeepEqual.ts
Labels: skip-release

#722 Var name improvement to reduce confusion
  packages/app/background-jobs-common/src/background-job-processor/monitoring/backgroundJobProcessorGetActiveQueueIds.ts
Labels: skip-release

#723 added after pagination schema
  packages/app/api-common/src/apiSchemas.ts
Labels: minor
