Repository lokalise/shared-ts-libs, pull requests merged in 2025-04, with the labels that each got.

#558 chore: Add summary to API contracts and pass-through description
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/types.ts
  packages/app/universal-ts-utils/src/public/api-contracts/__snapshots__/apiContracts.spec.ts.snap
  packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Labels: minor

#570 chore: Unblock npm release 1/2
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/types.ts
Labels: patch

#571 chore: Add summary to api-contracts 2/4
  packages/app/api-contracts/README.md
  packages/app/api-contracts/src/__snapshots__/apiContracts.spec.ts.snap
  packages/app/api-contracts/src/apiContracts.ts
Labels: patch

#572 chore: Add summary to api-contracts 3/4
  packages/app/universal-ts-utils/README.md
Labels: patch

#575 Test bot access token
  .github/workflows/release.api-common.yml
  .github/workflows/release.package.yml
  packages/app/api-common/vitest.config.ts
Labels: patch

#576 Test using bot access token
  .github/workflows/release.package.yml
  packages/app/api-common/vitest.config.ts
Labels: patch

#577 Revert changes on release actions
  .github/workflows/release.api-common.yml
  .github/workflows/release.package.yml
Labels: skip-release

#578 feat: First version of mockttp utils
  .github/workflows/release.mockttp-utils.yml
  packages/app/mockttp-utils/.gitignore
  packages/app/mockttp-utils/LICENSE.md
  packages/app/mockttp-utils/README.md
  packages/app/mockttp-utils/package.json
  packages/app/mockttp-utils/src/index.ts
  packages/app/mockttp-utils/src/mockttpUtils.spec.ts
  packages/app/mockttp-utils/src/mockttpUtils.ts
  packages/app/mockttp-utils/tsconfig.build.json
  packages/app/mockttp-utils/tsconfig.json
  packages/app/mockttp-utils/vitest.config.ts
Labels: minor

#579 feat: Implement msw support via universal-testing-utils, move mockttp-utils
  .github/workflows/release.universal-testing-utils.yml
  packages/app/universal-testing-utils/.gitignore
  packages/app/universal-testing-utils/LICENSE.md
  packages/app/universal-testing-utils/README.md
  packages/app/universal-testing-utils/package.json
  packages/app/universal-testing-utils/src/MockttpHelper.spec.ts
  packages/app/universal-testing-utils/src/MockttpHelper.ts
  packages/app/universal-testing-utils/src/MswHelper.spec.ts
  packages/app/universal-testing-utils/src/MswHelper.ts
  packages/app/universal-testing-utils/src/index.ts
  packages/app/universal-testing-utils/test/testContracts.ts
  packages/app/universal-testing-utils/tsconfig.build.json
  packages/app/universal-testing-utils/tsconfig.json
  packages/app/universal-testing-utils/vitest.config.ts
Labels: minor

#580 chore: Drop mockttp utils
  packages/app/mockttp-utils/.gitignore
  packages/app/mockttp-utils/LICENSE.md
  packages/app/mockttp-utils/README.md
  packages/app/mockttp-utils/package.json
  packages/app/mockttp-utils/src/index.ts
  packages/app/mockttp-utils/src/mockttpUtils.spec.ts
  packages/app/mockttp-utils/src/mockttpUtils.ts
  packages/app/mockttp-utils/tsconfig.build.json
  packages/app/mockttp-utils/tsconfig.json
  packages/app/mockttp-utils/vitest.config.ts
Labels: skip-release

#581 feat: Separate list of languages and locales supported by Lokalise
  packages/app/supported-languages/README.md
  packages/app/supported-languages/src/index.ts
  packages/app/supported-languages/src/lokaliseLanguages.ts
Labels: minor

#582 Feature/tsconfig es2023
  packages/dev/tsconfig/configs/base.json
  packages/dev/tsconfig/configs/build-app.json
  packages/dev/tsconfig/configs/build-private-lib.json
  packages/dev/tsconfig/configs/build-public-lib.json
  packages/dev/tsconfig/configs/bundler-dom.json
  packages/dev/tsconfig/configs/bundler.json
  packages/dev/tsconfig/configs/tsc-dom.json
  packages/dev/tsconfig/configs/tsc.json
  packages/dev/tsconfig/package.json
Labels: minor

#584 chore: Do not report muted UnrecoverableError
  packages/app/background-jobs-common/README.md
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.error.spec.ts
  packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
  packages/app/background-jobs-common/src/background-job-processor/utils.ts
  packages/app/background-jobs-common/src/errors/MutedUnrecoverableError.ts
  packages/app/background-jobs-common/src/index.ts
Labels: minor

#589 feat: Add support for tags
  packages/app/api-contracts/package.json
  packages/app/api-contracts/src/__snapshots__/apiContracts.spec.ts.snap
  packages/app/api-contracts/src/apiContracts.ts
Labels: minor

#588 Chore: revising vitest config
  packages/app/api-common/package.json
  packages/app/api-common/tsconfig.json
  packages/app/api-common/vitest.config.ts
  packages/app/api-contracts/package.json
  packages/app/api-contracts/tsconfig.json
  packages/app/api-contracts/vitest.config.ts
  packages/app/backend-http-client/package.json
  packages/app/backend-http-client/tsconfig.json
  packages/app/backend-http-client/vitest.config.ts
  packages/app/background-jobs-common/vitest.config.ts
  packages/app/context-fastify-plugins/vitest.config.ts
  packages/app/error-utils/package.json
  packages/app/error-utils/tsconfig.json
  packages/app/error-utils/vitest.config.ts
  packages/app/events-common/package.json
  packages/app/events-common/vitest.config.ts
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/tsconfig.json
  packages/app/fastify-api-contracts/vitest.config.ts
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/tsconfig.json
  packages/app/frontend-http-client/vitest.config.ts
  packages/app/healthcheck-utils/package.json
  packages/app/healthcheck-utils/vitest.config.ts
  packages/app/id-utils/package.json
  packages/app/id-utils/tsconfig.json
  packages/app/id-utils/vitest.config.ts
  packages/app/metrics-utils/package.json
  packages/app/metrics-utils/tsconfig.json
  packages/app/metrics-utils/vitest.config.ts
  packages/app/non-translatable-markup/package.json
  packages/app/non-translatable-markup/tsconfig.json
  packages/app/non-translatable-markup/vitest.config.ts
  packages/app/prisma-utils/tsconfig.json
  packages/app/prisma-utils/vitest.config.ts
  packages/app/script-utils/package.json
  packages/app/script-utils/tsconfig.json
  packages/app/script-utils/vitest.config.ts
  packages/app/supported-languages/package.json
  packages/app/supported-languages/tsconfig.json
  packages/app/supported-languages/vitest.config.ts
  packages/app/universal-testing-utils/package.json
  packages/app/universal-testing-utils/tsconfig.json
  packages/app/universal-testing-utils/vitest.config.ts
  packages/app/universal-ts-utils/package.json
  packages/app/universal-ts-utils/tsconfig.json
  packages/app/universal-ts-utils/vitest.config.ts
  packages/app/websockets-common/package.json
  packages/app/websockets-common/tsconfig.json
  packages/app/websockets-common/vitest.config.ts
Labels: skip-release

#593 Add test for type inference when handling multiple query values, separated by commas
  packages/app/frontend-http-client/package.json
  packages/app/frontend-http-client/src/client.spec.ts
Labels: skip-release

#592 Fastify API contracts Route type narrowing down types
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
  packages/app/fastify-api-contracts/src/types.ts
Labels: minor

#596 fix: Properly handle empty responses for non-payload routes
  packages/app/fastify-api-contracts/package.json
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
Labels: patch

#597 Fixing the route type to allow any type provider and logger
  packages/app/fastify-api-contracts/src/types.ts
Labels: patch

#601 * return false on empty healthcheck
  packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
  packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
  packages/app/healthcheck-utils/src/healthchecks.ts
Labels: major

#600 Feature: EXP-325 AWS config 2
  .github/workflows/release.aws-config.yml
  packages/app/aws-config/README.md
  packages/app/aws-config/package.json
  packages/app/aws-config/src/awsConfig.ts
  packages/app/aws-config/src/index.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsResolver.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/prehandlers/createRequestContextPreHandler.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/prehandlers/createRequestContextPreHandler.ts
  packages/app/aws-config/src/message-queue-toolkit/types.ts
  packages/app/aws-config/src/message-queue-toolkit/utils.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/utils.ts
  packages/app/aws-config/tests/FakeLogger.ts
Labels: major

#602 Fix typo in peer dep condition
  packages/app/aws-config/package.json
Labels: patch

#603 Feature/aws config adjustments
  packages/app/aws-config/src/event-routing/eventRoutingConfig.spec.ts
  packages/app/aws-config/src/event-routing/eventRoutingConfig.ts
  packages/app/aws-config/src/message-queue-toolkit/utils.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/utils.ts
Labels: minor

#604 Fixing issues with message types
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
  packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsResolver.spec.ts
  packages/app/aws-config/src/message-queue-toolkit/types.ts
Labels: patch

#605 feat Add extra msw test methods
  packages/app/universal-testing-utils/README.md
  packages/app/universal-testing-utils/src/MswHelper.spec.ts
  packages/app/universal-testing-utils/src/MswHelper.ts
  packages/app/universal-testing-utils/vitest.config.ts
Labels: minor

#606 Expose contract on a route
  packages/app/fastify-api-contracts/README.md
  packages/app/fastify-api-contracts/src/fastifyApiContracts.metadataMapper.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
  packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
Labels: minor

#608 Removing @lokalise/events-common
  .github/workflows/release.events-common.yml
  packages/app/events-common/.gitignore
  packages/app/events-common/LICENSE.md
  packages/app/events-common/README.md
  packages/app/events-common/package.json
  packages/app/events-common/src/baseEventSchemas.ts
  packages/app/events-common/src/index.ts
  packages/app/events-common/test/baseEventSchemas.spec.ts
  packages/app/events-common/tsconfig.build.json
  packages/app/events-common/tsconfig.json
  packages/app/events-common/vitest.config.ts
Labels: skip-release

#609 AP-6857 Allow aborting the request made by calling `sendPostWithProgress()`
  packages/app/frontend-http-client/README.md
  packages/app/frontend-http-client/src/client.spec.ts
  packages/app/frontend-http-client/src/client.ts
Labels: minor
